---
- name: Disable systemd-resolved to free port 53
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Remove systemd-resolved stub resolv.conf symlink
  file:
    path: /etc/resolv.conf
    state: absent

- name: Write static resolv.conf
  copy:
    content: |
      nameserver 1.1.1.1
      nameserver 9.9.9.9
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"