---
- name: Provision Orange Pi base system
  hosts: orangepi
  become: true

  roles:
    - { role: users, tags: [users] }
    - { role: packages, tags: [packages] }
    - { role: mounts, tags: [mounts] }
    - { role: docker, tags: [docker] }
    - { role: nfs, tags: [nfs] }
    - { role: nfs_server, tags: [nfs_server] }
    - { role: iac, tags: [iac] }
    - { role: stacks, tags: [stacks] }