system_user: moises
m2_uuid: "cb58afcf-a254-4835-993e-ac4fc1834140"

infra_path: "/home/{{ system_user }}/mnt/M2/iac"

docker_data_root: "/home/{{ system_user }}/mnt/M2/docker"

containerd_root: "/home/{{ system_user }}/mnt/M2/containerd"

symlinks:
  - { src: "/home/{{ system_user }}/mnt/M2/local", path: "/home/{{ system_user }}/local" }

docker_stacks:
  - portainer/stacks/portainer

nfs_export_path: "/home/{{ system_user }}/mnt/M2"
nfs_export_clients:
  - 192.168.1.133
  - 192.168.1.243
  - 192.168.1.244
  - 192.168.1.245

nfs_mounts:
  - { src: "192.168.1.20:/BAK", path: "/home/moises/mnt/BAK" }
  - { src: "192.168.1.20:/BAK3", path: "/home/moises/mnt/BAK3" }
  - { src: "192.168.1.245:/home/moises/mnt/BAK4", path: "/home/moises/mnt/BAK4" }
  - { src: "192.168.1.245:/home/moises/mnt/BAK5", path: "/home/moises/mnt/BAK5" }
  - { src: "192.168.1.245:/home/moises/mnt/BAK6", path: "/home/moises/mnt/BAK6" }
  - { src: "192.168.1.245:/home/moises/mnt/BAK7", path: "/home/moises/mnt/BAK7" }