---
- name: Create M2 mount point
  file:
    path: "/home/{{ system_user }}/mnt/M2"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"

- name: Mount M2 disk by UUID
  ansible.posix.mount:
    path: "/home/{{ system_user }}/mnt/M2"
    src: "UUID={{ m2_uuid }}"
    fstype: ext4
    opts: defaults,noatime
    state: mounted

- name: Create Docker data-root directory on M2
  file:
    path: "{{ docker_data_root }}"
    state: directory
    owner: root
    group: root
    mode: "0711"

- name: Create iac directory on M2
  file:
    path: "{{ infra_path }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: "0755"